name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      # Step 3: Debug Ruby Environment (Optional)
      - name: Check Ruby CSV
        run: ruby -e "require 'csv'" || echo 'CSV library not found'

      # Step 4: Install Jekyll and dependencies
      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use a stable Node.js version

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test
